name: Update Docker Hub Description

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'README.Docker.md'
  workflow_dispatch:

jobs:
  update-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dydydd/pandirectserver
          short-description: 'Emby 代理服务器，支持 123 网盘直链播放，极致优化播放速度'
          readme-filepath: ./README.Docker.md

